name: Post JSON File to Two URLs 

on: 
 push: 
  branches: 
   - main  # Runs only when pushing to the main branch 
 workflow_dispatch:  # Allows manual trigger 
 
jobs: 
 post_json: 
  runs-on: ubuntu-latest 
  steps: 
   - name: Checkout Repository 
     uses: actions/checkout@v3 
   - name: Send JSON Data to First URL 
     run: | 
      curl -X POST "https://:cdihsdZZTZKIKkOG-WJFzw@eu.tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:xYdGH7J0TXOtsgZctlrhzw/streams/AQAAAE8TCqPu00FdvHpI-VZeAekAAAAA" \
           -H "Content-Type: application/json" \
           -d @stream.json 
      
   - name: Send JSON Data to Second URL 
     run: | 
      curl -X POST "https://:p1vDsO10QPeMH3Lj_YWYJg@eu.tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:xYdGH7J0TXOtsgZctlrhzw/streams/AQAAAM2A7VuqgkL3ie7VwsiWL6oAAAAA" \
           -H "Content-Type: application/json" \
           -d @stream.json
